trigger:
  branches:
    include:
      - master    # ← make sure this matches what your DevOps connector is watching

pool:
  vmImage: 'windows-latest'

steps:
  # 1. Install Terraform
  - task: TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'latest'

  # 2. Terraform init & validate
  - script: |
      terraform init -backend=false
      terraform validate
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: 'Terraform Init & Validate'

  # 3. Run the MSDO IaC scan (findings won’t fail the build)
  - task: MicrosoftSecurityDevOps@1
    displayName: 'MSDO IaC Security Scan'
    inputs:
      categories: 'IaC'
      tools: 'terrascan,checkov'
      sourceDirectory: '$(Build.SourcesDirectory)'
      outputSarif: '$(Build.ArtifactStagingDirectory)/iac-scan.sarif'
      publish: true
      artifactName: 'CodeAnalysisLogs'
      failOnPolicyViolation: false
    continueOnError: true

  # 4. Copy the SARIF report into the staging folder (so Publish can find it)
  - task: CopyFiles@2
    displayName: 'Copy SARIF report to staging'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'        # adjust if your scan writes elsewhere
      Contents:      '**/iac-scan.sarif'
      TargetFolder:  '$(Build.ArtifactStagingDirectory)'

  # 5. Publish the SARIF as a build artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish CodeAnalysisLogs'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/iac-scan.sarif'
      ArtifactName:  'CodeAnalysisLogs'
